### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by prologic** [prologic/autodock#9]
Current roadmap:

- [ ] Port `autodock` core from Python to Go
- [ ] Port `autodock-logger` from Python to Go
- [ ] Port `autodock-cron` from Python to Go
- [ ] Build a `autodock-scale` plugin to support autoscaling of Containers or Swarm Services using at least Prometheus as a metrics source
- [ ] Support both Standalone Containers (in non-Swarm Mode) and Services (in Docker Swarm-Mode)

**Comment by prologic** [comment]
TODO: Test non-Swarm and Swarm usage and merge.
